//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Match
{
    public int HomeTeamScore { get; set; }
    public int HomeTeamId { get; set; }
    public int AwayTeamScore { get; set; }
    public int AwayTeamId { get; set; }
    public string MVPPlayer { get; set; }
}

public partial class Player
{
    public int TeamId { get; set; }
    public string PlayerName { get; set; }
    public int Age { get; set; }
    public int Weight { get; set; }
    public string BirthPlace { get; set; }
}

public partial class Team
{
    public int TeamId { get; set; }
    public string TeamName { get; set; }
    public string TeamWebSite { get; set; }
    public string TeamConference { get; set; }
    public string TeamLogo { get; set; }
}
